/**
 * ZenTube Extractor - Core Type Definitions
 * Unified Multi-Platform Media & Metadata Models (YouTube, SoundCloud, Bandcamp)
 */

export type StreamingPlatform = 'youtube' | 'soundcloud' | 'bandcamp';

export type DeliveryType = 'PROGRESSIVE' | 'DASH' | 'HLS';

export interface Thumbnail {
  url: string;
  width: number;
  height: number;
}

export interface StreamFormat {
  itag: number;
  url: string;
  mimeType: string;
  container: 'mp4' | 'webm' | '3gp' | 'm4a' | 'mp3' | 'unknown';
  codecs: string;
  bitrate: number;
  averageBitrate?: number;
  contentLength?: number;
  qualityLabel?: string;
  approxDurationMs?: number;
}

export interface VideoStream extends StreamFormat {
  type: 'video_only' | 'video_audio';
  width: number;
  height: number;
  fps: number;
  resolution: string; // e.g., '1080p', '720p', '480p'
  isDrc?: boolean;
}

export interface AudioStream extends StreamFormat {
  type: 'audio_only';
  audioQuality: string;
  audioSampleRate: number;
  audioChannels: number;
  loudnessDb?: number;
}

export interface SubtitleTrack {
  name: string;
  languageCode: string;
  baseUrl: string;
  isTranslatable?: boolean;
  isAutoGenerated?: boolean;
}

export interface VideoChapter {
  title: string;
  startTimeSeconds: number;
  thumbnailUrl?: string;
}

export interface TranscriptSegment {
  startMs: number;
  durationMs: number;
  timeFormatted: string;
  text: string;
}

export interface StreamInfo {
  platform?: StreamingPlatform;
  id: string;
  url: string;
  title: string;
  description: string;
  duration: number; // in seconds
  viewCount: number;
  uploadDate?: string;
  isLive: boolean;
  uploader: {
    id: string;
    name: string;
    url: string;
    avatarUrl?: string;
    verified: boolean;
    subscriberCountText?: string;
  };
  thumbnails: Thumbnail[];
  videoStreams: VideoStream[];
  audioStreams: AudioStream[];
  subtitles: SubtitleTrack[];
  chapters: VideoChapter[];
  dashManifestUrl?: string;
  hlsManifestUrl?: string;
  relatedVideos: RelatedVideoItem[];
}

export interface RelatedVideoItem {
  id: string;
  title: string;
  duration?: string;
  viewCountText?: string;
  uploaderName: string;
  uploaderUrl?: string;
  thumbnails: Thumbnail[];
}

export interface SearchFilter {
  type?: 'all' | 'video' | 'channel' | 'playlist' | 'track' | 'album' | 'artist';
  platform?: StreamingPlatform;
  sortBy?: 'relevance' | 'upload_date' | 'view_count' | 'rating';
}

export interface SearchVideoItem {
  type: 'video';
  platform?: StreamingPlatform;
  id: string;
  title: string;
  descriptionSnippet?: string;
  durationText?: string;
  viewCountText?: string;
  publishedTimeText?: string;
  uploader: {
    name: string;
    id?: string;
    avatarUrl?: string;
    verified: boolean;
  };
  thumbnails: Thumbnail[];
}

export interface SearchChannelItem {
  type: 'channel';
  platform?: StreamingPlatform;
  id: string;
  name: string;
  handle?: string;
  descriptionSnippet?: string;
  videoCountText?: string;
  subscriberCountText?: string;
  thumbnails: Thumbnail[];
}

export interface SearchPlaylistItem {
  type: 'playlist';
  platform?: StreamingPlatform;
  id: string;
  title: string;
  videoCountText?: string;
  uploaderName?: string;
  thumbnails: Thumbnail[];
}

export interface SearchTrackItem {
  type: 'track';
  platform?: StreamingPlatform;
  id: string;
  title: string;
  artist: string;
  durationText?: string;
  streamUrl?: string;
  thumbnails: Thumbnail[];
}

export type SearchItem = SearchVideoItem | SearchChannelItem | SearchPlaylistItem | SearchTrackItem;

export interface SearchResult {
  query: string;
  platform?: StreamingPlatform;
  items: SearchItem[];
  continuationToken?: string;
}

export interface ChannelInfo {
  platform?: StreamingPlatform;
  id: string;
  name: string;
  handle?: string;
  description: string;
  subscriberCountText?: string;
  videoCountText?: string;
  avatarUrl?: string;
  bannerUrl?: string;
  verified: boolean;
  tabs: string[];
  recentVideos: SearchVideoItem[];
}

export interface PlaylistInfo {
  platform?: StreamingPlatform;
  id: string;
  title: string;
  description?: string;
  uploaderName?: string;
  videoCount: number;
  viewCountText?: string;
  lastUpdated?: string;
  thumbnails: Thumbnail[];
  videos: SearchVideoItem[];
  continuationToken?: string;
}

export interface CommentItem {
  id: string;
  authorName: string;
  authorAvatarUrl?: string;
  authorChannelId?: string;
  content: string;
  publishedTimeText: string;
  likeCountText?: string;
  replyCount?: number;
  repliesToken?: string;
}

export interface ShortsItem {
  id: string;
  title: string;
  channelName: string;
  channelId: string;
  avatarUrl?: string;
  thumbnailUrl?: string;
  viewCountText?: string;
}

// SoundCloud Data Models
export interface SoundCloudTrack {
  id: string;
  urn: string;
  url: string;
  title: string;
  artist: string;
  artistUrl: string;
  duration: number; // in seconds
  streamUrl: string;
  artworkUrl?: string;
  waveformUrl?: string;
  playbackCount?: number;
  likesCount?: number;
  genre?: string;
  createdAt?: string;
}

// Bandcamp Data Models
export interface BandcampTrack {
  id: string;
  title: string;
  trackNum?: number;
  duration: number;
  streamUrl: string;
  artist: string;
  albumTitle?: string;
  lyrics?: string;
  artworkUrl?: string;
}

export interface BandcampAlbum {
  id: string;
  url: string;
  title: string;
  artist: string;
  artistUrl: string;
  releaseDate?: string;
  artworkUrl?: string;
  tracks: BandcampTrack[];
}

// Downloader Progress Model
export interface DownloadProgress {
  bytesDownloaded: number;
  totalBytes: number;
  percent: number;
  speedBytesPerSec: number;
}
